### ISSUE TITLE
FR: Add Applyable trait back

### ISSUE THREAD

**Issue by maxhbooth** [lesurp/OptionalStruct#22]
I'd like to be able to use optional_structs in generics, but since the `Applyable` trait got removed in https://github.com/lesurp/OptionalStruct/commit/a0ad1298273e405dddab59a78aa2ce47827c3893, it doesn't look like I can do that anymore.  Would it be possible for that trait to be added back in?

**Comment by lesurp** [comment]
Hey, I reintroduced the trait, hopefully this covers your use case.
Please note that the trait was renamed to `Applicable` (traded consistency for better spelling).
