### ISSUE TITLE
Can't use with other derive attributes

### ISSUE THREAD

**Issue by norcalli** [lesurp/OptionalStruct#8]
The parser `panic!`s incorrectly when it encounters attributes that it doesn't recognize, but this isn't correct since those attributes could belong to other derive macros, like serde.

```rust
#[derive(Serialize, Deserialize, OptionalStruct)]
#[serde(rename_all = "camelCase")]
#[optional_name = "PartialChatState"]
#[optional_derive(Serialize, Deserialize)]
struct ChatState {
    messages: Vec<ChatMessage>,
    visitor_name: String,
}
```

Output
```
error: proc-macro derive panicked
  --> src/main.rs:68:10
   |
68 | #[derive(OptionalStruct)]
   |          ^^^^^^^^^^^^^^
   |
   = help: message: Only optional_derive are supported

error: aborting due to previous error

```

**Comment by detly** [comment]
Did this ever make it into a release?

**Comment by doivosevic** [comment]
can we somehow make this work with serde? I really need some features like deny_unknown_fields @lesurp 

august 2018. is last version change if im correct
